export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const LOGIN = '/login'
export const CREAR_TIENDA ='/crear-tienda'
export const SLIDE = '/slide'
export const LANDING = '/';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const PASSWORD_FORGET = '/pw-forget';